Controllers/GlobalSettingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace LoLBoostMarketCMS.Controllers
{
    [Authorize]
    public class GlobalSettingsController : Controller
    {
        [AllowAnonymous]
        [HttpPost]
        public IActionResult GetSettingsWindowModal()
        {
            return PartialView("_SettingsWindowModal");
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult ChangeLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return Ok(returnUrl);
        }
    }
}

Views/GlobalSettings/_GlobalSettings.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<link rel="stylesheet" href="~/dist/css/global-settings.min.css">
<script src="~/dist/js/global-settings.min.js"></script>

<div id="global-settings-btn" data-href="@Url.Action("GetSettingsWindowModal","GlobalSettings")">
    <button id="global-settings-layout" class="btn">@Localizer["Settings"] </button>
    <i id="global-settings-icon" class="fas fa-cogs"></i>
</div>

Views/GlobalSettings/_LanguageSettings.cshtml
@using LoLBoostMarketCMS.Settings
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<LocalizationSettings> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var currentLanguage = requestCulture.RequestCulture.Culture.Name;
}

<div id="language-settings-container">
    <div class="languages-part">
        <div id="languages">
            @{
                foreach (var language in LocOptions.Value.AllSupportedLanguages)
                {
                    <div class="language-item waves-effect @(language.Culture == currentLanguage ? "selected" : string.Empty)" data-culture="@language.Culture">
                        <div class="language-flag">
                            <img src="@Url.Content(language.FlagImgUrl)" />
                        </div>
                        <div class="language-name">@language.LanguageName</div>
                    </div>
                }
            }
        </div>
    </div>

    <div class="language-settings-footer">
        <button id="save-language-btn" data-href="@Url.Action("ChangeLanguage","GlobalSettings")" class="btn blue-gradient waves-effect">@Localizer["Save"]</button>
    </div>
</div>

Views/GlobalSettings/_SettingsWindowModal.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<div id="settings-window" class="custom-fancybox-content">
    <div class="stw-header">
        <i id="stw-header-icon" class="fas fa-cogs"></i>
        <div class="stw-title">@Localizer["Settings"]</div>
        <i id="stw-close-btn" class="fas fa-times"></i>
    </div>

    <div class="or-spacer">
        <div class="mask"></div>
    </div>

    <div class="stw-body">
        <div id="stw-tab-control">
            <div class="stw-tab-item active" data-tab-index="0">
                <i class="swt-tab-item-icon fas fa-globe"></i>
                <div class="swt-tab-item-text">@Localizer["Language"]</div>
            </div>

        </div>

        <div class="or-spacer-vertical left">
            <div class="mask"></div>
        </div>

        <div id="stw-tab-content">
            <div class="stw-tab-content active" data-tab-index="0">
                @await Html.PartialAsync("_LanguageSettings")
            </div>
        </div>
    </div>
</div>